apiVersion: v1
kind: Namespace
metadata:
  name: hsof
  labels:
    name: hsof
    app.kubernetes.io/name: hsof
    app.kubernetes.io/part-of: hybrid-search-optimal-features
    environment: production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hsof-service-account
  namespace: hsof
  labels:
    app.kubernetes.io/name: hsof
    app.kubernetes.io/component: service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hsof-role
  namespace: hsof
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "secrets", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hsof-role-binding
  namespace: hsof
subjects:
- kind: ServiceAccount
  name: hsof-service-account
  namespace: hsof
roleRef:
  kind: Role
  name: hsof-role
  apiGroup: rbac.authorization.k8s.io